### ISSUE TITLE
No module named 'lcap'

### ISSUE THREAD

**Issue by sonovice** [csteinmetz1/st-ito#1]
Hi and thank you very much for your presentation at this year's ISMIR conference and for open sourcing your code!

However, I am running into issues running the `run_optim` script. It seems to look for a specific encoder model named `lcap` that is nowhere to be found.

Here is the complete traceback:
```
./scripts/run_optim.sh
/opt/homebrew/Caskroom/miniconda/base/envs/stito/lib/python3.11/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
ParametricEQ: low_shelf_gain_db = 0.5
ParametricEQ: low_shelf_cutoff_freq = 0.01507537688442211
ParametricEQ: low_shelf_q_factor = 0.15564102564102564
ParametricEQ: band0_gain_db = 0.5
ParametricEQ: band0_cutoff_freq = 0.028056112224448898
ParametricEQ: band0_q_factor = 0.15564102564102564
ParametricEQ: band1_gain_db = 0.5
ParametricEQ: band1_cutoff_freq = 0.09819639278557114
ParametricEQ: band1_q_factor = 0.15564102564102564
ParametricEQ: band2_gain_db = 0.5
ParametricEQ: band2_cutoff_freq = 0.2985971943887776
ParametricEQ: band2_q_factor = 0.15564102564102564
ParametricEQ: band3_gain_db = 0.5
ParametricEQ: band3_cutoff_freq = 1.0
ParametricEQ: band3_q_factor = 0.15564102564102564
ParametricEQ: high_shelf_gain_db = 0.5
ParametricEQ: high_shelf_cutoff_freq = 0.0449438202247191
ParametricEQ: high_shelf_q_factor = 0.15564102564102564

Compressor: threshold_db = 1.0
Compressor: ratio = 0.15789473684210525
Compressor: attack_ms = 0.009009009009009009
Compressor: release_ms = 0.09090909090909091

Distortion: drive_db = 0.5
Distortion: output_gain_db = 0.5

Delay: delay_seconds = 0.494949494949495
Delay: feedback = 0.4736842105263158
Delay: mix = 0.5

Reverb: room_size = 0.5
Reverb: damping = 0.5
Reverb: wet_dry = 0.5
Reverb: width = 0.5

Traceback (most recent call last):
  File "Data/ISMIR2024/repos/st-ito/scripts/run_optim.py", line 540, in <module>
    model = load_param_model(use_gpu=args.use_gpu)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Data/ISMIR2024/repos/st-ito/st_ito/utils.py", line 529, in load_param_model
    module = import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/stito/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lcap'
```

Is there anything I can do to make it work? Any help is highly appreciated.

**Comment by csteinmetz1** [comment]
Hey, I just made some fixes. Can you pull and test again?

**Comment by sonovice** [comment]
Thank you, that indeed fixed the loading issue. Now it shows a missing key error:
```
File "/Users/simon/Desktop/ISMIR2024/repos/st-ito/st_ito/style_transfer.py", line 77, in process_audio
    for name in plugin["parameter_names"]:
                ~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'parameter_names'
```

This is my call:
```bash
python scripts/run_optim.py \
"/Users/simon/Desktop/ISMIR2024/repos/st-ito/query.wav" \
"/Users/simon/Desktop/ISMIR2024/repos/st-ito/target.mp3" \
--algorithm es \
--effect-type basic \
--dropout 0.0 \
--max-iters 25 \
--savepop \
--metric param
```

EDIT:
The effect in question is an instance of `st_ito.effects.BasicParametricEQ`. The dictionary looks like this:
```python
{
    'class_path': <class 'st_ito.effects.BasicParametricEQ'>,
    'num_params': 18,
    'num_channels': 1,
    'fixed_parameters': {},
    'instance': <st_ito.effects.BasicParametricEQ object at 0x16c145650>
}
```

**Comment by csteinmetz1** [comment]
Thanks for testing. I just pushed another fix, let me know if that works.

**Comment by sonovice** [comment]
Thanks, the code now seems to run correctly. :)
